"""delete post title

Revision ID: 941c1a3443fa
Revises: 0bfe362713f8
Create Date: 2018-05-03 11:11:28.644645

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '941c1a3443fa'
down_revision = '0bfe362713f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('title', mysql.TEXT(), nullable=True))
    # ### end Alembic commands ###
